### ISSUE TITLE
Target [Nexmo\Client\Credentials\CredentialsInterface] is not instantiable while building [Nexmo\Client]. 

### ISSUE THREAD

**Issue by ghost** [Nexmo/nexmo-laravel#6] opened 2016-12-12 09:13 UTC
When I try using the Facade: 
Nexmo::message()->send([
    'to' => '14845551244',
    'from' => '16105552344',
    'text' => 'Using the facad to send a mesage.'
]);

Note: I have added:

Nexmo\Laravel\NexmoServiceProvider::class    to my providers array

'Nexmo' => \Nexmo\Laravel\Facade\Nexmo::class  to my alias

Am using Laravel 5.3

**Comment by atapatel** [comment] 2017-02-24 08:26
+1 i am also facing this issue.

**Comment by tjlytle** [comment] 2017-02-24 13:28
@aliuwahab21 @atapatel see [this related issue](https://github.com/Nexmo/nexmo-laravel/issues/3).

**Comment by leandrit1** [comment] 2017-03-24 14:14
Hi @tjlytle , I am having the same problem, and furthermore I have noticed that the nexmo.php even though I followed all the steps, when I run php artisan vendor:publish  the nexmo.php file can not be found on the config/nexmo.php as we see it in some tutorials but we find it just in the vendor/nexmo/laravel/config/nexmo.php

Target [Nexmo\Client\Credentials\CredentialsInterface] is not instantiable while building [Nexmo\Client].

**Comment by tjlytle** [comment] 2017-03-27 16:10
@LeandritGo What version of Laravel are you using?

**Comment by leandrit1** [comment] 2017-03-27 16:53
Laravel 5.3

On 27 Mar 2017 18:10, "Tim Lytle" <notifications@github.com> wrote:

@LeandritGo <https://github.com/LeandritGo> What version of Laravel are you
using?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Nexmo/nexmo-laravel/issues/6#issuecomment-289502366>,
or mute the thread

**Comment by leandrit1** [comment] 2017-03-31 23:14
Are there any news regarding the issue?

**Comment by tjlytle** [comment] 2017-03-31 23:44
@LeandritGo I can't replicate, but if it's not creating `config/nexmo.php` just copy the file from `vendor/nexmo/laravel/config/nexmo.php` to your config directory.

And if `artisan vendor:publish` isn't creating the config file, seems like there's something missing in your `config/app.php` (Laravel doesn't know about the Nexmo Service Provider).

**Comment by tjlytle** [comment] 2017-06-18 20:21
@afolson See @enasellithy's comment in the closed thread (https://github.com/Nexmo/nexmo-laravel/issues/3). I can't replicate unless I drop the client from the providers config. Any ideas? I'm sure there could be better error handling as well.

**Comment by afolson** [comment] 2017-06-18 21:07
I tried just now and was unable to reproduce on L5.3 or L5.4 unless I dropped the client from the providers array in `config/app.php`. Additionally, I was able to verify that `artisan vendor:publish` puts a `nexmo.php` file in the config directory. 

It seems like people are using various versions of the Laravel package AND the client, or possibly just using `nexmo/client` instead of `nexmo/laravel`. Would someone mind running `composer update nexmo/laravel` and making sure that `"nexmo/laravel": "^0.4.0"` appears in `composer.json` and that you see a block similar to this in `composer.lock`:

<img width="496" alt="screenshot 2017-06-18 13 54 57" src="https://user-images.githubusercontent.com/2797769/27264170-d412507c-542d-11e7-82b3-f1abc76c3d09.png">

Note that `nexmo/laravel` is pulling in `nexmo/client` and they have the same version number here. In theory, adding/removing packages via composer should re-generate the autoload file, but for good measure you may want to run `composer dump-auto` just in case.

If it's still not working after all of that we can debug deeper 🐛

**Comment by tjlytle** [comment] 2017-06-18 21:25
@afolson Wonder if there's a way to catch that (including `nexmo/client` but trying to invoke using the service provider, and provide a better error message.

**Comment by leandrit1** [comment] 2017-06-18 22:27
I fixed my issue by running php artisan config:clear , it took me a bunch of time as I ran cache:clear and was not thinking of using config:clear.

**Comment by mheap** [comment] 2017-10-16 14:03
As we've not been able to reproduce this, I'm going to close the issue. We can link and reopen in future if required.

**Closed as completed by mheap** 2017-10-16 14:03 UTC

**Comment by erickbrz** [comment] 2018-02-11 23:09
solved for me, i had in my config/nexmo.php ('signature_secret' => xxxxxx), after deleted the line, send sms!
